# Author:  DINDIN Meryll
# Date:    09 July 2019
# Project: AsTeR

users:
- username: 'admin'
  password: 'admin'
  firstname: 'admin'
  lastname: 'admin'
  email: 'admin@berkeley.edu'
- username: 'guest'
  password: 'guest'
  firstname: 'guest'
  lastname: 'guest'
  email: 'guest@berkeley.edu'

units:
- unit_id: '310bee28ecb9459e9184ed226d729d1f'
  unit_type: 'police'
  unit_name: 'Police Patrol | Unit 3'
  longitude: -122.35689904651082
  latitude: 37.73681896347287
  status: 'active'
  target: '-122.4284612378737:37.75182473669415'
  path: 'none'
- unit_id: '340bb30f0d8d49169c5218c6a3f4ca2c'
  unit_type: 'ambulance'
  unit_name: 'Ambulance | Unit 7'
  longitude: -122.45180930817796
  latitude: 37.78643389570368
  status: 'active'
  target: 'none'
  path: 'none'
- unit_id: '5d87b0f6ae464929adb491099fdf4d33'
  unit_type: 'firefighter'
  unit_name: 'Firefighters | Unit 5'
  longitude: -122.48051188957147
  latitude: 37.77899290319121
  status: 'active'
  target: 'none'
  path: 'none'


