# Author:  DINDIN Meryll
# Date:    09 July 2019
# Project: AsTeR

users:
- username: 'admin'
  password: 'admin'
  firstname: 'admin'
  lastname: 'admin'
  email: 'admin@berkeley.edu'
- username: 'guest'
  password: 'guest'
  firstname: 'guest'
  lastname: 'guest'
  email: 'guest@berkeley.edu'