# Author:  DINDIN Meryll
# Date:    09 July 2019
# Project: AsTeR

users:
- username: 'admin'
  password: 'admin'
  fullname: 'admin'
  emailing: 'admin@berkeley.edu'
- username: 'guest'
  password: 'guest'
  fullname: 'guest'
  emailing: 'guest@berkeley.edu'