# Author:  DINDIN Meryll, RADERMECKER Oskar
# Date:    16 July 2019
# Project: AsTeR

api_key: 'a18d20d47cc642deaf83865b50e69575'
sql_api: 'https://servicesql-comedic-wallaby.mybluemix.net'
secret_key: '5y2LF4Q8znxec'
googlemaps_api: 'AIzaSyDuDzzvbvZ26mJUB3xz4E9uTlRt8EBAcPI'